version: '3.8'

services:
  frontend:
    image: conversations-editor_frontend
    build: 
      context: ./frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - DOCKER_ENV=true
    networks:
      - app-network
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      backend:
        condition: service_started

  backend:
    image: conversations-editor_backend
    build: 
      context: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ${WORKSPACE_DIR:-./workspace}:/app/workspace
      - ./backend:/app
    working_dir: /app
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s

networks:
  app-network:
    driver: bridge

volumes:
  workspace: 